### ISSUE TITLE
Add experiences section

### ISSUE THREAD

**Issue by ShyrenMore** [DevelopersLeague/StudNet#1]
**Add an experience section** where student can share their experiences about various events, student-program, internships, etc. 
**Each post** in this section should have a **label of either event, student-program, internship.**

**Comment by yohannathomas** [comment]
As a graduate student, writing my dissertation has been one of the most challenging tasks I've faced. I found half-life calculator with steps [https://calculatorprofessional.com/half-life-calculator](https://calculatorprofessional.com/half-life-calculator) extremely useful. It’s a fantastic tool for managing my time effectively, especially when dealing with complex calculations related to my research. The interface is user-friendly, and the precise results have been invaluable. For anyone embarking on their dissertation journey, leveraging such reliable tools can significantly streamline the process, allowing more focus on content quality and research depth.

**Comment by ShyrenMore** [comment]
@yohannathomas please spam elsewhere
